// swagger: https://api.mypurecloud.com/api/v2/docs/swagger
package bigqueryupload

import (
	"fmt"

	"cloud.google.com/go/bigquery"
)

func createConversationDetailsSchema() bigquery.Schema {
	fmt.Println("Create Schema for conversation details table")

	conversationDetailsSchema := bigquery.Schema{
		{Name: "conversations",
			Type:     bigquery.RecordFieldType,
			Repeated: true,
			Schema: bigquery.Schema{
				{Name: "conferenceStart", Type: bigquery.TimestampFieldType},
				{Name: "conversationEnd", Type: bigquery.TimestampFieldType},
				{Name: "conversationId", Type: bigquery.StringFieldType},
				{Name: "conversationInitiator", Type: bigquery.StringFieldType},
				{Name: "conversationStart", Type: bigquery.TimestampFieldType},
				{Name: "customerParticipation", Type: bigquery.BooleanFieldType},
				{Name: "divisionIds", Type: bigquery.StringFieldType, Repeated: true},
				{Name: "externalTag", Type: bigquery.StringFieldType},
				{Name: "knowledgeBaseIds", Type: bigquery.StringFieldType, Repeated: true},
				{Name: "mediaStatsMinConversationMos", Type: bigquery.FloatFieldType},
				{Name: "mediaStatsMinConversationRFactor", Type: bigquery.FloatFieldType},
				{Name: "originatingDirection", Type: bigquery.StringFieldType},
				{Name: "selfServed", Type: bigquery.BooleanFieldType},
				{Name: "evaluations",
					Type:     bigquery.RecordFieldType,
					Repeated: true,
					Schema: bigquery.Schema{
						{Name: "assigneeApplicable", Type: bigquery.BooleanFieldType},
						{Name: "assigneeId", Type: bigquery.StringFieldType},
						{Name: "calibrationId", Type: bigquery.StringFieldType},
						{Name: "contextId", Type: bigquery.StringFieldType},
						{Name: "deleted", Type: bigquery.BooleanFieldType},
						{Name: "evaluationId", Type: bigquery.StringFieldType},
						{Name: "evaluationStatus", Type: bigquery.StringFieldType},
						{Name: "evaluatorId", Type: bigquery.StringFieldType},
						{Name: "eventTime", Type: bigquery.TimestampFieldType},
						{Name: "formId", Type: bigquery.StringFieldType},
						{Name: "formName", Type: bigquery.StringFieldType},
						{Name: "queueId", Type: bigquery.StringFieldType},
						{Name: "released", Type: bigquery.BooleanFieldType},
						{Name: "rescored", Type: bigquery.BooleanFieldType},
						{Name: "userId", Type: bigquery.StringFieldType},
						{Name: "oTotalCriticalScore", Type: bigquery.IntegerFieldType},
						{Name: "oTotalScore", Type: bigquery.IntegerFieldType},
					}},
				{Name: "surveys",
					Type:     bigquery.RecordFieldType,
					Repeated: true,
					Schema: bigquery.Schema{
						{Name: "eventTime", Type: bigquery.TimestampFieldType},
						{Name: "queueId", Type: bigquery.StringFieldType},
						{Name: "surveyCompletedDate", Type: bigquery.TimestampFieldType},
						{Name: "surveyFormContextId", Type: bigquery.StringFieldType},
						{Name: "surveyFormId", Type: bigquery.StringFieldType},
						{Name: "surveyFormName", Type: bigquery.StringFieldType},
						{Name: "surveyId", Type: bigquery.StringFieldType},
						{Name: "surveyPartialResponse", Type: bigquery.BooleanFieldType},
						{Name: "surveyPromoterScore", Type: bigquery.IntegerFieldType},
						{Name: "surveyStatus", Type: bigquery.StringFieldType},
						{Name: "surveyType", Type: bigquery.StringFieldType},
						{Name: "userId", Type: bigquery.StringFieldType},
						{Name: "oSurveyTotalScore", Type: bigquery.IntegerFieldType},
					}},
				{Name: "resolutions",
					Type:     bigquery.RecordFieldType,
					Repeated: true,
					Schema: bigquery.Schema{
						{Name: "eventTime", Type: bigquery.TimestampFieldType},
						{Name: "queueId", Type: bigquery.StringFieldType},
						{Name: "userId", Type: bigquery.StringFieldType},
						{Name: "nNextContactAvoided", Type: bigquery.IntegerFieldType},
					}},
				{Name: "participants",
					Type:     bigquery.RecordFieldType,
					Repeated: true,
					Schema: bigquery.Schema{
						{Name: "externalContactId", Type: bigquery.StringFieldType},
						{Name: "externalOrganizationId", Type: bigquery.StringFieldType},
						{Name: "flaggedReason", Type: bigquery.StringFieldType},
						{Name: "participantId", Type: bigquery.StringFieldType},
						{Name: "participantName", Type: bigquery.StringFieldType},
						{Name: "purpose", Type: bigquery.StringFieldType},
						{Name: "teamId", Type: bigquery.StringFieldType},
						{Name: "userId", Type: bigquery.StringFieldType},
						{Name: "sessions",
							Type:     bigquery.RecordFieldType,
							Repeated: true,
							Schema: bigquery.Schema{
								{Name: "activeSkillIds", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "acwSkipped", Type: bigquery.BooleanFieldType},
								{Name: "addressFrom", Type: bigquery.StringFieldType},
								{Name: "addressOther", Type: bigquery.StringFieldType},
								{Name: "addressSelf", Type: bigquery.StringFieldType},
								{Name: "addressTo", Type: bigquery.StringFieldType},
								{Name: "agentAssistantId", Type: bigquery.StringFieldType},
								{Name: "agentBullseyeRing", Type: bigquery.IntegerFieldType},
								{Name: "agentOwned", Type: bigquery.BooleanFieldType},
								{Name: "ani", Type: bigquery.StringFieldType},
								{Name: "assignerId", Type: bigquery.StringFieldType},
								{Name: "authenticated", Type: bigquery.BooleanFieldType},
								{Name: "bargedParticipantId", Type: bigquery.StringFieldType},
								{Name: "bcc", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "callbackNumbers", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "callbackScheduledTime", Type: bigquery.TimestampFieldType},
								{Name: "callbackUserName", Type: bigquery.StringFieldType},
								{Name: "cc", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "cleared", Type: bigquery.BooleanFieldType},
								{Name: "coachedParticipantId", Type: bigquery.StringFieldType},
								{Name: "cobrowseRole", Type: bigquery.StringFieldType},
								{Name: "cobrowseRoomId", Type: bigquery.StringFieldType},
								{Name: "deliveryStatus", Type: bigquery.StringFieldType},
								{Name: "deliveryStatusChangeDate", Type: bigquery.TimestampFieldType},
								{Name: "destinationAddresses", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "direction", Type: bigquery.StringFieldType},
								{Name: "dispositionAnalyzer", Type: bigquery.StringFieldType},
								{Name: "dispositionName", Type: bigquery.StringFieldType},
								{Name: "dnis", Type: bigquery.StringFieldType},
								{Name: "edgeId", Type: bigquery.StringFieldType},
								{Name: "eligibleAgentCounts", Type: bigquery.IntegerFieldType, Repeated: true},
								{Name: "extendedDeliveryStatus", Type: bigquery.StringFieldType},
								{Name: "flowInType", Type: bigquery.StringFieldType},
								{Name: "flowOutType", Type: bigquery.StringFieldType},
								{Name: "journeyActionId", Type: bigquery.StringFieldType},
								{Name: "journeyActionMapId", Type: bigquery.StringFieldType},
								{Name: "journeyActionMapVersion", Type: bigquery.IntegerFieldType},
								{Name: "journeyCustomerId", Type: bigquery.StringFieldType},
								{Name: "journeyCustomerIdType", Type: bigquery.StringFieldType},
								{Name: "journeyCustomerSessionId", Type: bigquery.StringFieldType},
								{Name: "journeyCustomerSessionIdType", Type: bigquery.StringFieldType},
								{Name: "mediaBridgeId", Type: bigquery.StringFieldType},
								{Name: "mediaCount", Type: bigquery.IntegerFieldType},
								{Name: "mediaType", Type: bigquery.StringFieldType},
								{Name: "messageType", Type: bigquery.StringFieldType},
								{Name: "monitoredParticipantId", Type: bigquery.StringFieldType},
								{Name: "outboundCampaignId", Type: bigquery.StringFieldType},
								{Name: "outboundContactId", Type: bigquery.StringFieldType},
								{Name: "outboundContactListId", Type: bigquery.StringFieldType},
								{Name: "peerId", Type: bigquery.StringFieldType},
								{Name: "protocolCallId", Type: bigquery.StringFieldType},
								{Name: "provider", Type: bigquery.StringFieldType},
								{Name: "recording", Type: bigquery.BooleanFieldType},
								{Name: "remote", Type: bigquery.StringFieldType},
								{Name: "remoteNameDisplayable", Type: bigquery.StringFieldType},
								{Name: "removedSkillIds", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "requestedRoutings", Type: bigquery.StringFieldType, Repeated: true},
								{Name: "roomId", Type: bigquery.StringFieldType},
								{Name: "routingRing", Type: bigquery.IntegerFieldType},
								{Name: "routingRule", Type: bigquery.StringFieldType},
								{Name: "routingRuleType", Type: bigquery.StringFieldType},
								{Name: "screenShareAddressSelf", Type: bigquery.StringFieldType},
								{Name: "screenShareRoomId", Type: bigquery.StringFieldType},
								{Name: "scriptId", Type: bigquery.StringFieldType},
								{Name: "selectedAgentId", Type: bigquery.StringFieldType},
								{Name: "selectedAgentRank", Type: bigquery.IntegerFieldType},
								{Name: "sessionDnis", Type: bigquery.StringFieldType},
								{Name: "sessionId", Type: bigquery.StringFieldType},
								{Name: "sharingScreen", Type: bigquery.StringFieldType},
								{Name: "skipEnabled", Type: bigquery.StringFieldType},
								{Name: "timeoutSeconds", Type: bigquery.StringFieldType},
								{Name: "usedRouting", Type: bigquery.StringFieldType},
								{Name: "videoAddressSelf", Type: bigquery.StringFieldType},
								{Name: "videoRoomId", Type: bigquery.StringFieldType},
								{Name: "waitingInteractionCounts", Type: bigquery.IntegerFieldType, Repeated: true},
								{Name: "agentGroups",
									Type:     bigquery.RecordFieldType,
									Repeated: true,
									Schema: bigquery.Schema{
										{Name: "agentGroupId", Type: bigquery.StringFieldType},
										{Name: "agentGroupType", Type: bigquery.StringFieldType},
									}},
								{Name: "proposedAgents",
									Type:     bigquery.RecordFieldType,
									Repeated: true,
									Schema: bigquery.Schema{
										{Name: "agentRank", Type: bigquery.IntegerFieldType},
										{Name: "proposedAgentId", Type: bigquery.StringFieldType},
									}},
								{Name: "mediaEndpointStats",
									Type:     bigquery.RecordFieldType,
									Repeated: true,
									Schema: bigquery.Schema{
										{Name: "codecs", Type: bigquery.StringFieldType, Repeated: true},
										{Name: "discardedPackets", Type: bigquery.IntegerFieldType},
										{Name: "duplicatePackets", Type: bigquery.IntegerFieldType},
										{Name: "eventTime", Type: bigquery.TimestampFieldType},
										{Name: "invalidPackets", Type: bigquery.IntegerFieldType},
										{Name: "maxLatencyMs", Type: bigquery.IntegerFieldType},
										{Name: "minMos", Type: bigquery.FloatFieldType},
										{Name: "minRFactor", Type: bigquery.FloatFieldType},
										{Name: "overrunPackets", Type: bigquery.IntegerFieldType},
										{Name: "receivedPackets", Type: bigquery.IntegerFieldType},
										{Name: "underrunPackets", Type: bigquery.IntegerFieldType},
									}},
								{Name: "flow",
									Type: bigquery.RecordFieldType,
									Schema: bigquery.Schema{
										{Name: "endingLanguage", Type: bigquery.StringFieldType},
										{Name: "entryReason", Type: bigquery.StringFieldType},
										{Name: "entryType", Type: bigquery.StringFieldType},
										{Name: "exitReason", Type: bigquery.StringFieldType},
										{Name: "flowId", Type: bigquery.StringFieldType},
										{Name: "flowName", Type: bigquery.StringFieldType},
										{Name: "flowType", Type: bigquery.StringFieldType},
										{Name: "flowVersion", Type: bigquery.StringFieldType},
										{Name: "issuedCallback", Type: bigquery.BooleanFieldType},
										{Name: "recognitionFailureReason", Type: bigquery.StringFieldType},
										{Name: "startingLanguage", Type: bigquery.StringFieldType},
										{Name: "transferTargetAddress", Type: bigquery.StringFieldType},
										{Name: "transferTargetName", Type: bigquery.StringFieldType},
										{Name: "transferType", Type: bigquery.StringFieldType},
										{Name: "outcomes",
											Type:     bigquery.RecordFieldType,
											Repeated: true,
											Schema: bigquery.Schema{
												{Name: "flowOutcome", Type: bigquery.StringFieldType},
												{Name: "flowOutcomeEndTimestamp", Type: bigquery.TimestampFieldType},
												{Name: "flowOutcomeId", Type: bigquery.StringFieldType},
												{Name: "flowOutcomeStartTimestamp", Type: bigquery.TimestampFieldType},
												{Name: "flowOutcomeValue", Type: bigquery.StringFieldType},
											}},
									}},
								{Name: "metrics",
									Type:     bigquery.RecordFieldType,
									Repeated: true,
									Schema: bigquery.Schema{
										{Name: "emitDate", Type: bigquery.StringFieldType},
										{Name: "name", Type: bigquery.StringFieldType},
										{Name: "value", Type: bigquery.IntegerFieldType},
									}},
								{Name: "segments",
									Type:     bigquery.RecordFieldType,
									Repeated: true,
									Schema: bigquery.Schema{
										{Name: "audioMuted", Type: bigquery.BooleanFieldType},
										{Name: "conference", Type: bigquery.BooleanFieldType},
										{Name: "destinationConversationId", Type: bigquery.StringFieldType},
										{Name: "destinationSessionId", Type: bigquery.StringFieldType},
										{Name: "disconnectType", Type: bigquery.StringFieldType},
										{Name: "errorCode", Type: bigquery.StringFieldType},
										{Name: "groupId", Type: bigquery.StringFieldType},
										{Name: "q850ResponseCodes", Type: bigquery.StringFieldType, Repeated: true},
										{Name: "queueId", Type: bigquery.StringFieldType},
										{Name: "requestedLanguageId", Type: bigquery.StringFieldType},
										{Name: "requestedRoutingSkillIds", Type: bigquery.StringFieldType, Repeated: true},
										{Name: "requestedRoutingUserIds", Type: bigquery.StringFieldType, Repeated: true},
										{Name: "segmentEnd", Type: bigquery.TimestampFieldType},
										{Name: "segmentStart", Type: bigquery.TimestampFieldType},
										{Name: "segmentType", Type: bigquery.StringFieldType},
										{Name: "sipResponseCodes", Type: bigquery.IntegerFieldType, Repeated: true},
										{Name: "sourceConversationId", Type: bigquery.StringFieldType},
										{Name: "sourceSessionId", Type: bigquery.StringFieldType},
										{Name: "subject", Type: bigquery.StringFieldType},
										{Name: "videoMuted", Type: bigquery.BooleanFieldType},
										{Name: "wrapUpCode", Type: bigquery.StringFieldType},
										{Name: "wrapUpNote", Type: bigquery.StringFieldType},
										{Name: "wrapUpTags", Type: bigquery.StringFieldType, Repeated: true},
										{Name: "scoredAgents",
											Type:     bigquery.RecordFieldType,
											Repeated: true,
											Schema: bigquery.Schema{
												{Name: "agentScore", Type: bigquery.IntegerFieldType},
												{Name: "scoredAgentId", Type: bigquery.StringFieldType},
											}},
										{Name: "properties",
											Type:     bigquery.RecordFieldType,
											Repeated: true,
											Schema: bigquery.Schema{
												{Name: "property", Type: bigquery.StringFieldType},
												{Name: "propertyType", Type: bigquery.StringFieldType},
												{Name: "value", Type: bigquery.StringFieldType},
											}},
									}},
							}},
					}},
				{Name: "aggregations",
					Type:     bigquery.RecordFieldType,
					Repeated: true,
					Schema: bigquery.Schema{
						{Name: "type", Type: bigquery.StringFieldType},
						{Name: "dimension", Type: bigquery.StringFieldType},
						{Name: "metric", Type: bigquery.StringFieldType},
						{Name: "count", Type: bigquery.IntegerFieldType},
						{Name: "results",
							Type:     bigquery.RecordFieldType,
							Repeated: true,
							Schema: bigquery.Schema{
								{Name: "count", Type: bigquery.IntegerFieldType},
								{Name: "value", Type: bigquery.StringFieldType},
								{Name: "gte", Type: bigquery.NumericFieldType},
								{Name: "lt", Type: bigquery.NumericFieldType},
							}},
					}},
			}},
		{Name: "totalHits", Type: bigquery.IntegerFieldType},
	}

	return conversationDetailsSchema
}
